# Generated by Django 3.1.2 on 2020-11-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='user',
        ),
    ]
