# Generated by Django 3.1.2 on 2020-10-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
